general.import = ["~/.config/alacritty/themes/alacritty-theme/tokyo_night.toml"]

[font]
size = 10.0

[font.bold]
family = "alacritty-terminal-font"

[font.bold_italic]
family = "alacritty-terminal-font"

[font.italic]
family = "alacritty-terminal-font"

[font.normal]
family = "alacritty-terminal-font"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 123
lines = 28

[window.padding]
x = 3
y = 3
